---
# tasks file for install_docker
  - include_tasks: debian_tasks.yml
    when: ansible_os_family == 'Debian'

  - include_tasks: RHEL_tasks.yml
    when: ansible_os_family == 'RedHat'

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Install Docker Compose
    pip:
      name: docker-compose