---
# tasks file for install_app
  - name: Create group
    group:
      name: '{{ group_name }}'
      state: present

  - name: Create User
    user:
      name: '{{ user_name }}'
      group: '{{ group_name }}'
      state: present

  - name: Copy docker compose file
    template:
      src: docker-compose.yml.j2
      dest: '{{ app_dir }}/docker-compose.yml'
      owner: '{{user_name}}'
      group: '{{group_name}}'
      mode: '0644'

  - name: Deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: '{{ app_dir }}/'
      files:
      - docker-compose.yml